# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/csci-435-hw7',
                'doc_host': 'https://kateebalint.github.io',
                'git_url': 'https://github.com/kateebalint/csci-435-hw7',
                'lib_path': 'csci_435_hw7'},
  'syms': {'csci_435_hw7.core': {'csci_435_hw7.core.foo': ('core.html#foo', 'csci_435_hw7/core.py')}}}